### PR TITLE
NTAuthentication, NetType, LastWriteTime and Archive attribute

### PR DESCRIPTION
**Pull request by mitrov**

### CODE REVIEW

**Comment by jhoek** [comment]
I like your changes! :-)

- The DateTime is now passed as a parameter to Export-NavApplicationObject? I feel the function should determine the date/time by itself based on the object's properties in the database? After all, the input doesn't necessarily come from Get-NAVApplicationObjectInfo?

- Along the same lines, would it make sense to let the Modified object property control the Archive file attribute?

- If Start-NAVDevelopmentClient now supports ntauthentication and nettype, shouldn't Get-NAVDatabaseConnectionConfig also be modified? We need to include the extra pieces of information in the configuration file's header?

**Comment by mitrov** [comment]
Valid points!
Please check again.
I hope the overall export performance is not much worse now since we read from the object table twice

**Comment by jhoek** [comment]
Yep, that's much better, thanks! 

I was thinking (sorry for changing my mind) that maybe we should allow Modified and DateTime to be passed in as parameters (in case the input comes from Get-NavApplicationObjectInfo *or* the user wants to control this information from the command line). If nothing is specified, we could retrieve it from the database. Or do you think that is confusing?

The date/time from the object properties in the database may not be in the same time zone as the person running this script, so when setting the file date/time, should we take local time into account? Although you'd need to *know* the time zone the server is in - I don't see a way to determine that otherwise?

If NTAuthenication is false in the database configs, how would you specify a user name/password?

And finally, maybe we need a ValidateSet attribute for the NetType in Start-NAVDevelopmentClient? After all, only a limited set of strings will be valid?

Sorry to be such a nit-picker! ;-) Still busy working on my IDYN stuff, so I won't be able to really dive into this until end of next week, I'm afraid... :-(

**Comment by mitrov** [comment]
Sorry for my late reply. I was busy with the NAV2016 release ;-)

Ok ... let's see....
-> Modified and DateTime to be passed in as parameters. Confusing?
That's very subjective ;-) 
Powershell cmdlets have usually a *LOT* of parameters... but as long as they are optional I don't care about them, -> I'll update the script

>Different time zones between object creator and object exporter
Now THAT would make things confusing ;-) I would not worry about that. Using the NAV Object DateTime property is the only way to go IMHO. 

>NTAuthenication is false in the database configs, how would you specify a user name/password?
The  reason why I implemented it is: if you have a classic server running (not a local fdb file) ...  you  need to pass NTAuthentication as parameter to Classic Client... otherwise the database does not open. On the other hand I would never store a database login and password in a config file.
But yes... if someone(?) wants that... it would have to be stored in the databases - config file I guess.

> ValidateSet attribute for the NetType in Start-NAVDevelopmentClient? 
You are right. -> I'll update the script

**Comment by jhoek** [comment]
Merged in your changes. Hope to be able to try them out this weekend.

**Pull request merged**
